### ISSUE TITLE
No VIM keys? what da!

### ISSUE THREAD

**Issue by ant0n-anon** [Siriusmart/youtube-tui#1]
Can we all please be sensible? Can we please use vim keybinds, let's not be wild men. We are all gentlemen.

**Comment by Siriusmart** [comment]
sure will add them

**Comment by Siriusmart** [comment]
done, vim keys added as default alongside arrow keys (note that if you want to add any keys you can go edit `~/.config/youtube-tui/keybindings.yml`, but if you think there can be any improvement to the default config/settings, feel free to open an issue, thx <3)
