### ISSUE TITLE
Fails to compile on Windows 10 system

### ISSUE THREAD

**Issue by mantasarm** [Siriusmart/youtube-tui#17]
Building the project with `cargo install youtube-tui` or building from source on Windows 10 throws the same error.

![image](https://user-images.githubusercontent.com/34283640/206843020-91a08e32-0f76-4a14-be93-1488aa9a30c8.png)

How should this be resolved?

**Comment by Siriusmart** [comment]
You can make compile on windows using this command, as mentioned in [*the user manual*](https://siriusmart.github.io/youtube-tui/installation.html)
```
cargo install youtube-tui --no-default-features
```

However, it may still not run after successful compiling (according to [*this issue*](https://github.com/Siriusmart/youtube-tui/issues/12))
