### ISSUE TITLE
cp URL to clipboard?

### ISSUE THREAD

**Issue by se7en-x230** [Siriusmart/youtube-tui#18]
- Copy URL: ${xclip} ${embed-url}

how would I create a custom command to copy the URL to my clipboard?

**Comment by Siriusmart** [comment]
it didn't work because piping `|` was broken.

i've fixed it in the latest commit, you can install it with `cargo install --git 'https://github.com/siriusmart/youtube-tui'`, and the command now is either `run echo ${url or embed-url} | xclip` or `cp ${url}`

hope that works

**Comment by se7en-x230** [comment]
![shop-2023-01-13-10-02](https://user-images.githubusercontent.com/69777713/212228988-3377df71-719f-406b-a2f0-7026480e3f2f.png)

Perfect now ; are also working 

Thanks

**Comment by se7en-x230** [comment]
![shop-2023-01-13-10-39](https://user-images.githubusercontent.com/69777713/212231815-75354327-3232-49b0-b9a7-167f12b4fa58.png)

And I installed konsole with the gruvbox theme, exclusivity for youtube-tui for the image support

**Comment by kqvanity** [comment]
@se7en-x230  Is there to yank the hover title as well?

**Comment by Siriusmart** [comment]
> [@se7en-x230](https://github.com/se7en-x230) Is there to yank the hover title as well?

by that you mean the hover-url equivalent for title right?

**Comment by Siriusmart** [comment]
i can't believe im pushing a commit to this repo in 2025, but here it is

https://siriusmart.github.io/youtube-tui/config/commands.html#env-reference

Added variables for `hover-id`, `hover-title`, `hover-channel-id`, `hover-channel`

**Comment by kqvanity** [comment]
@Siriusmart 

Thanks for the commit. It did span multiple lines so sure a good deal of work. It works really great now.

Please keep up the good work
