### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Siriusmart/youtube-tui#21]
The readme clams the project is [dependency-free](https://github.com/Siriusmart/youtube-tui/tree/7b5aa671fe144bb7e696b9ccdde6a9205c54fdb4#dependency-free), but it looks like their are some dependency, without the project does not work (additional to mpv).
* libsixel
* ~~konsole~~

This should be mention.

**Comment by Siriusmart** [comment]
by dependency free i meant the prebuilt binary can be ran without libsixel, only compiling requires libsixel. (a minimal version can be compiled without libsixel using `--no-default-features`.

but if crates.io is where people install from, i'll sure add a note explaining to what extent the tui is "depdency-free"

**Comment by LuckyTurtleDev** [comment]
> i meant the prebuilt binary can be ran without libsixel, only compiling requires libsixel.

It can be build without libsixel, but it can not be run without it. Because sixel-sys do ugly stuff, with linking.

**Comment by msrd0** [comment]
I have opened an issue with sixel-sys, however that library hasn't been updated in 5 years so I'm not sure if that issue is going to be fixed: https://github.com/AdnoC/sixel-sys/issues/3
