### ISSUE TITLE
invalide type: map, expected a sequence

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Siriusmart/youtube-tui#23]
If I select the channel and switch to video section, I get the following error.
I was not able to found a  channel, without this issue.
![image](https://user-images.githubusercontent.com/44570204/218513798-53ff20c6-ac25-431f-aef3-0b5d2a5ca105.png)

**Comment by Siriusmart** [comment]
This isn't an issue of the tui, as explained in #20

my suggestion is same as in issue 20 - try  use a different invidious instance
