### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by LuckyTurtleDev** [Siriusmart/youtube-tui#25]
The readme claims the project is dependency-free, but it looks like libxcb is also needed.

**Comment by msrd0** [comment]
To be precise, this is required as a dependency of the `clipboard` crate that you depend on.

**Comment by Siriusmart** [comment]
alr im just gonna remove the claim and give a list of dependencies in the user manual later

**Comment by Siriusmart** [comment]
reopening this to keep track of things

**Comment by Siriusmart** [comment]
I'm currently thinking about removing `clipboard` as a dependency crate, forcing users to use platform specific tools like `xclip` or `wl-clipboard`.

Here are some of the reasons:
- The crate only supports x11 clipboards, so it will not work on pure wayland systems
- Users can do the exact same thing using as mentioned, platform specific tools like `xclip` or `wl-clipboard`.
- Dependency free :D

What do u think

**Comment by Siriusmart** [comment]
nvm im just gonna do it anyways

**Comment by Siriusmart** [comment]
wait no then that would remove pasting on searchbar ok im keeping it
