### ISSUE TITLE
doc: tty env progs

### ISSUE THREAD

**Issue by edrex** [Siriusmart/youtube-tui#28]
Hi, I just installed `youtube-tui` and it looks fantastic! I use newpipe, and this seems to offer a similar feature set for term. 🥇 💯 🏆 🍰 ❤️ 

Anyway, I'm currently working in on a host in tmux on TTY, and the default settings expect GUI. We should document alt settings that do some sort of job supervising, maybe using a `youtube-tui` tmux session. I have some experience doing that, and could contrib. Thoughts?

**Comment by edrex** [comment]
Or just a section in the docs, to start. I was wanting to check with you before going forward, to see if you had any particular preferences for which tools. I spent some time evaluating [Zellij](https://zellij.dev/) last night, and concluded that it's a strict upgrade over tmux, so I was thinking to document config to open audio streams in an existing zellij session (just `zellij run -- cmd`). Also, any obstacles to just calling mpv etc directly, and waiting for it to exit? That honestly seems like a good default, since everyone has their own term emulator preference (kitty, wezterm, foot, konsole, etc). https://man.archlinux.org/man/i3-sensible-terminal.1.en is nice although unfortunately it's not installed by default anywhere.

**Comment by Siriusmart** [comment]
seems cool, but I don't really use those tools (tmux, or zellij).

currently I'm in an exam situation, and I have no commits on hold not committed, so there shouldn't be a possibility of merge conflicts. If that sounds good you can start editing `/docs` anytime if you want to, or tell me if I misunderstood anything.

**Comment by Siriusmart** [comment]
No pressure, but how's the progress?

Also, just want to let you know that the repo - including the docs has been modified just now, so if you are still doing it don't forget to git pull or something.

**Comment by Siriusmart** [comment]
dw it has already been put onto nixos repos see [installation](https://siriusmart.github.io/youtube-tui/installation.html#installation-on-nixos)

i'll close the issue for now as it doesn't seem necessary anymore

**Comment by edrex** [comment]
test

**Comment by edrex** [comment]
> already been put onto nixos repos

Yes, it's already in nixpkgs like [everything](https://repology.org/repositories/statistics/newest). I meant adding a config module to nix home-manager.

> i'll close the issue for now as it doesn't seem necessary anymore

Adding example config that doesn't assume a specific terminal emulator is installed still seems very worthwhile, to avoid the need for customization in most cases (maybe one has been added since I filed tho, haven't checked)

**Comment by Siriusmart** [comment]
A config repo seems to be a good idea, config profiles would also be a good idea. But that seems like a lot of work, so maybe a post 1.0, non default feature while I work on missing core features such as subscriptions.

*I also got another idea of making a TUI client template extensible by wasm, just like how [weechat](https://weechat.org) did it, but there are no plans and I currently have no idea how to do that.*

---

I originally thought that getting the default term is really complicated, `$TERM` thinks I'm using `xterm-256color`, I'll figure out a way to do that without introducing new dependencies as compiling is already so painfully slow.

![image](https://user-images.githubusercontent.com/71584876/236269080-7663274f-9f7d-4989-8473-b1e9a8148900.png)

**Comment by Siriusmart** [comment]
`$TERMINAL` does not exist for me, it is stored somewhere in KDE settings idk

**Comment by edrex** [comment]
It's an optional thing users can set. Usually you'd use it with a default value eg `${TERMINAL:-xterm}` in bash.

Check out how i3-sensible-terminal does it: https://github.com/i3/i3/blob/next/i3-sensible-terminal
