### ISSUE TITLE
Terminal Support

### ISSUE THREAD

**Issue by dostoievsky** [Siriusmart/youtube-tui#32]
Hey guys! I have the following question:
This support any terminal? Or it is needed to be a GPU powered like Kitty or Alacrity?

**Comment by Siriusmart** [comment]
Basically any, Linux is definitely working, perhaps Macs, but it doesn't seem to be working on windows, according to some issues long time ago, but that's not problem with the terminal. There are no plans to make it work on Windows.

The TUI can work with any terminal emulators, and even tty. The experience would be better in terminals with [sixel support](https://saitoha.github.io/libsixel), image rendering as a whole can be disabled in `main.yml` if you don't like the half block image rendering.

**Comment by dostoievsky** [comment]
I didn't tested the tui yet because of this question. I case I do not using a terminal with sixel support (I am currently using urxvt, and already found a sixel extension, but I've been thinking of using terminator those later days), we can open pop-ups of the videos, like, pipe it to something like VLC?

I'll test it soon! You think those questions could be good details to be placed at README? I also can contribute with that after see how it works here.

**Comment by Siriusmart** [comment]
commands are defined in [commands.yml](https://siriusmart.github.io/youtube-tui/config/commands.html), you can change how the tui plays the video by changing the config file, but i dont think vlc can play videos directly from youtube by default

**Comment by Siriusmart** [comment]
I didn't read the full thread, but it seems like kitty doesn't like obeying to standards.
https://github.com/kovidgoyal/kitty/issues/2511

**Comment by Siriusmart** [comment]
if you would want to use a minimal emulator, I suggest alarcitty-sixel or foot

**Comment by Neurognostic** [comment]
> kitty doesn't like obeying to standards.

Sixel is not an agreed upon standard for doing terminal graphics, there is no agreement, Sixel is just the oldest.

Kitty is not the only terminal that implements the [Kitty Graphics Protocol](https://sw.kovidgoyal.net/kitty/graphics-protocol/).

With Kitty you can play video directly in the terminal frame with mpv's [kitty video output driver](https://github.com/mpv-player/mpv/blob/master/video/out/vo_kitty.c).

**Comment by ryanmusante** [comment]
I use kitty. I found that the keybindings work better if you change from defaults
