### ISSUE TITLE
[feat]: addition of common keybinds

### ISSUE THREAD

**Issue by justchokingaround** [Siriusmart/youtube-tui#35]
It would be great to see more common keybinds be added to the TUI, such as:

- `Ctrl + Backspace` and `Ctrl + w` : delete one word
- `Ctrl + u` : clear whole line
- `gg` and `G` : go to first and last line
- `h` and `l` : previous page and next page (without prompting, as it currently does)

I also think that the following defaults would be an improvement for the UX:

- On launch, have the search bar be automatically focused and be in insert mode. That way the user can launch the application and directly start typing a query.
- After a user inputs a query and gets the search results, I think it is preferable for the user to be in insert mode in the window that lists the results, that way they can directly start navigating them.
- After a user selects an entry from the list, I think it is preferable for the user to be in insert mode in the window that lists the media options (Play video, Play audio etc.)
- I also think it would be a great addition if the user could use the `Backspace` keybind in insert mode when in the media options window, that way they don't have to press escape an additional time.

Overall, these are somewhat optional changes, so feel free to reject any of them, however they would save the user a few keystrokes here and there, which is always nice.

Additionally, I think the keybinds implementation done in this TUI could serve as a good guideline, I find it quite intuitive to use etc:
https://github.com/aome510/spotify-player/tree/master#commands

Also, as a side note, running `youtube-tui help` in the terminal doesn't work, and that's what the user is told to do after running `:help` in the TUI.

**Comment by Siriusmart** [comment]
- `Ctrl +w` and `Ctrl + u` just implemented
- `gg` would not be possible with the current keybindings handler, and I forgot what the code was supposed to do, so I'm not gonna try implementing it
- currently `h` and `l` goes to the first and last time in a list, it does not prompt. a more general approach make it so that you can control cursor movement using commands, so assigning `right ;; select` to `l` would basically be the same as going to the next page

**Comment by justchokingaround** [comment]
oh ok, that's good to know, i will remap it

**Comment by Siriusmart** [comment]
> On launch, have the search bar be automatically focused and be in insert mode. That way the user can launch the application and directly start typing a query.

Can be implemented using the "move cursor with command" thing, I'll do that later

> After a user inputs a query and gets the search results, I think it is preferable for the user to be in insert mode in the window that lists the results, that way they can directly start navigating them.

Again, same solution

> After a user selects an entry from the list, I think it is preferable for the user to be in insert mode in the window that lists the media options (Play video, Play audio etc.)

Same solution

> I also think it would be a great addition if the user could use the Backspace keybind in insert mode when in the media options window, that way they don't have to press escape an additional time.

Can make it so that the selected item does not "eat" your key input

**Comment by Siriusmart** [comment]
> Can make it so that the selected item does not "eat" your key input

That done

**Comment by Siriusmart** [comment]
All done, now just install the tui from git

```sh
cargo install --git https://github.com/Siriusmart/youtube-tui
```

and then regenerate the config files to see how everything is laid out by default.

**Comment by Siriusmart** [comment]
can you send me your config setup? i'm not a big keybindings user and i dont really know what would be a "sane" default

**Comment by justchokingaround** [comment]
the current default config doesn't work for me when i try to open a video, even though the provider is set to `YouTube` by default
![image](https://github.com/Siriusmart/youtube-tui/assets/44473782/911461fc-7887-451f-8127-d965f3180c6d)

**Comment by justchokingaround** [comment]
in the meantime, i will just change the invidious instance and test everything else, i see there are some subscribe to channel and save to library new features, which seem really cool. i'll send the config a bit later, once i'm done with testing everything

**Comment by justchokingaround** [comment]
here is some feedback from my testing, feel free to ignore any parts of it, there is quite a lot, sorry about that

1) after choosing view channel, it would probably make more sense to have the cursor be focused on the `Main - Videos - Playlists` bar, rather than the channel box, since it doesn't seem to have any actions associated with it.  
2) in the case that a channel doesn't have any playlists, but the user chooses to go to the playlists tab, the program crashes
3) the boxes in the feed view don't implement j and k navigation, only arrow keys seem to currently work
4) in the feed view, when selecting a video, the videos seem to lack description, date etc, which i think is quite useful information to have displayed
5) in the feed view, the videos list view should be sorted by date, rather than having chunks of videos from each channel (which seem to be sorted by date)
6) after saving a video to the library, and then removing it from the library, i think it would be reasonable to untoggle it as a bookmark (by default)
7) when selecting the history tab in the main view, the cursor should be focused on the videos list view, rather than the search bar
8) could be cool if there was an option to go the beginning of a line, that way the `<C-a>` and `<C-e>` keybinds can be configured
9) configuring `<C-Backspace>` to delete a word doesn't work, but mapping `<A-Backspace>` to delete a word does work
10) using the 1 code to map `Shift + key` doesn't work for some actions, such as for example `MoveRight` and `MoveLeft`, i wanted to use `Shift + J` and `Shift + K` for these actions (on a side note, i also couldn't figure out how to bind a key to multiple actions, for instance, `MoveRight` and then `Select`, to quickly navigate)

i attached my complete current config below, the only files which i didn't change from the defaults, were pages.yml and search.yml

https://transfer.sh/wqPlT0WCRL/youtube-tui.zip

thank you for everything you've done so far with this project, it's really impressive !

**Comment by Siriusmart** [comment]
> after choosing view channel, it would probably make more sense to have the cursor be focused on the Main - Videos - Playlists bar, rather than the channel box, since it doesn't seem to have any actions associated with it.

Default config has been updated for this, now they key inputs when the page loads are `Down > Enter > Up` (I also planned to add a commands menu for the useless channel item, maybe then it will get selected instead).

> in the case that a channel doesn't have any playlists, but the user chooses to go to the playlists tab, the program crashes

That is now fixed

> the boxes in the feed view don't implement j and k navigation, only arrow keys seem to currently work

It now does

> in the feed view, when selecting a video, the videos seem to lack description, date etc, which i think is quite useful information to have displayed

It could be because there is not enough height for the stuff to display, I would be making a scroll option for the iteminfo later

> in the feed view, the videos list view should be sorted by date, rather than having chunks of videos from each channel (which seem to be sorted by date)

the "all feeds" thing does have all videos from all the different channels sorted by published date, wdym

> after saving a video to the library, and then removing it from the library, i think it would be reasonable to untoggle it as a bookmark (by default)

The menu doesn't know whether the item is toggled or not, I'll add a thing later to do that (like how `${provider}` works)

> when selecting the history tab in the main view, the cursor should be focused on the videos list view, rather than the search bar

I've changed the defaults so that only on first launch will you focus on the searchbar, afterwards everytime you load the main menu page you will focus in the item list

> could be cool if there was an option to go the beginning of a line, that way the <C-a> and <C-e> keybinds can be configured

ok

> configuring <C-Backspace> to delete a word doesn't work, but mapping <A-Backspace> to delete a word does work

I tried but the termial seemed to think that C-Backspace is the same as `h`, so the default keybinding is `C-w`

> using the 1 code to map Shift + key doesn't work for some actions, such as for example MoveRight and MoveLeft, i wanted to use Shift + J and Shift + K for these actions (on a side note, i also couldn't figure out how to bind a key to multiple actions, for instance, MoveRight and then Select, to quickly navigate)

To map a shifted key you will need something like `'K': 1: KeyAction`, note that the key itself has to be in uppercase

Also it would be massively complicated if I were to change the keybindings system to allow multiple inputs, for that go use commandbindings and the `:key` command

**Comment by Siriusmart** [comment]
also your link to the config files doesnt work, you can just upload the zip file to here in this github issue

**Comment by Siriusmart** [comment]
again, the latest version can be installed with git

**Comment by justchokingaround** [comment]
here is the zip, i'll answer the other questions later today when i get home
[]()![youtube-tui.zip](https://github.com/Siriusmart/youtube-tui/files/12061202/youtube-tui.zip)

**Comment by ryanmusante** [comment]
How do I disable keybinds for partuclar items in the keybindings.yml? For some I want it zeroed out.

**Comment by Siriusmart** [comment]
> How do I disable keybinds for partuclar items in the keybindings.yml? For some I want it zeroed out.

that would not be possible as for now, can u give more detail on what r u gonna use it for and why would it be useful?

**Comment by ryanmusante** [comment]
Actually, reason for request is probably due to a bug in kitty terminal. I get hotkey conflicts, like when typing in something in the query box. Lowercase "k" won't print, I have to force a capital "K"

**Comment by Siriusmart** [comment]
what I could do is to add a "hard remap" layer above all, which force converts a key to another key, it would be a pretty simple fix.

also just curious you can type 'k' outside of the tui right? cuz I encountered a problem where C-backspace got mapped to something else in the tui, prob because of some weird terminal standard back in the days

**Comment by ryanmusante** [comment]
"k" works outside the tui (within a standard kitty term), but within this section as listed below it won't.

![youtube-tui](https://github.com/Siriusmart/youtube-tui/assets/26808646/8cc5f2e7-1a00-42cc-b2cd-11847a0a1aa6)

**Comment by Siriusmart** [comment]
check out `~/.config/remap.yml` in latest git version, u can prob remap `k` to some other keys, however inconvienient that may sound, it gives u an actual way of typing the character

**Comment by ryanmusante** [comment]
Got it, thanks. That will be enough to mitigate the issue.

**Comment by Siriusmart** [comment]
inactive thread closed, i think :D
