### ISSUE TITLE
[feat]: user account

### ISSUE THREAD

**Issue by justchokingaround** [Siriusmart/youtube-tui#36]
Sorry if this has been discussed or announced anywhere, I just couldn't find any information about it, but is the addition of users' youtube accounts planned? Being able to use a TUI application that supports viewing all of the channels you've subscribed to, playlists you have saved and videos you've liked, as well as being able to do those things inside of it, would be amazing.

**Comment by Siriusmart** [comment]
this tui does not use the official youtube api, instead uses the [invidious api](https://docs.invidious.io/api/) to access youtube content.
as a result it would be near impossible to impl youtube accounts without rewriting the core of the program.

what you could do, is to sync the `~/.local/share/youtube-tui/` directory on exiting the tui if you are planing to share your library across all your devices

note that it is important to only sync after the tui has exited, or else the files might still being moved around, i assume you can do that with a bit of bash aliases
