### ISSUE TITLE
Search bar won't let me type 'j' and 'k' directly

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [Siriusmart/youtube-tui#37]
v0.7.4
archlinux

It appears that I'm unable to enter the letters 'j' and 'k' directly into the search bar because they're being interpreted as Vim movement keys instead of literal letters. However, if I hold down the Ctrl or Alt key, I'm able to type these letters as normal. Interestingly, I don't have any issues typing the letters 'h' and 'l'. This problem seems to have started with version 0.7.4.

**Comment by Siriusmart** [comment]
now fixed by preventing keys representing a character (with no key modifiers or just shift) be captured as keybinginds

**Comment by Siriusmart** [comment]
`cargo install --git https://github.com/Siriusmart/youtube-tui` btw

**Comment by U1s2e3r4n5a6m7e** [comment]
I can confirm that it's working now. Thank you for the quick fix and for this program. I love using it; it's nice to have and use.

**Comment by Siriusmart** [comment]
thx
