### ISSUE TITLE
How to change video resolution

### ISSUE THREAD

**Issue by itsaj26744** [Siriusmart/youtube-tui#40]
How to adjust video default resolution as it loads video in high resolution and I have limited bandwidth.

**Comment by Siriusmart** [comment]
under [`commands.yml`](https://siriusmart.github.io/youtube-tui/config/commands.html) you should see the command used for playing videos, you may change up the command to play a lower resolution according to [this post](https://old.reddit.com/r/linuxquestions/comments/clyt9z/how_do_i_make_mpv_select_1080p_or_less_for_video/)
