### ISSUE TITLE
cargo install fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by hobo1618** [Siriusmart/youtube-tui#42]
Hello!

I tried installing with cargo but I've run into this error:
```error: linking with `cc` failed: exit status: 1```
```note: /usr/bin/ld: cannot find -lmpv: No such file or directory```

Any idea what's gone wrong here? Let me know if you need more info.

Thanks so much!

OS-release:
```
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
```

**Comment by hobo1618** [comment]
thanks for the quick reply!
Unfortunately the following didn't work (always the same error output):

- build from source -> `cargo install --git ...`
- mpv was already installed -> `/usr/bin/mpv`

I'm not sure how to run an arch binary on my system. I tried building from source for the latest release and that didn't work, and Ubuntu apparently doesn't know what to do with the downloaded file `youtube-tui-full-arch-x86_64`

On the plus side, `cargo install youtube-tui --no-default-features` works. Later today/tomorrow I can try installing with different features to see which one is causing the problem and let you know. 

If I can provide more detailed info, let me know what might be useful.

Thanks a bunch.

**Comment by Siriusmart** [comment]
I was able to recreate that issue on an Ubuntu 22.04 VM, the package you are missing seemed to be `libmpv-dev`, please reply if that is (or isn't) the case.

**Comment by hobo1618** [comment]
works! thanks so much
