### ISSUE TITLE
Version Mismatch Error and Thread Panic on Debian 12

### ISSUE THREAD

**Issue by 5n00py** [Siriusmart/youtube-tui#46]
Hey there, this looks like a great project and I am trying to make it run on Debian 12 via cargo install.

However, I am experiencing a version missmatch error and a thread panic when I try to run `youtube-tui` (version 0.8.0) on Debian 12. It looks like the error is related to a discrepancy between the linked and loaded version of the `mpv` library. I don't see how to quickly fix this and I am not interested in upgrading or downgrading my mpv setup.

My environment:
- OS: Debian 12, version 12.4
- Kernel: 6.1.0-16-amd64
- Rustc Version: 1.74.0
- Terminal: alacritty
- Shell: Zsh
- youtube-tui
- mpv Version detailed: mpv --version
    mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
     built on UNKNOWN
    FFmpeg library versions:
       libavutil       57.28.100
       libavcodec      59.37.100
       libavformat     59.27.100
       libswscale      6.7.100
       libavfilter     8.44.100
       libswresample   4.7.100
    FFmpeg version: 5.1.4-0+deb12u1

After installation of libmpv-dev the installation compiled properly with one warning: warning: the following packages contain code that will be rejected by a future version of Rust: traitobject v0.1.0. When I try to start it from the terminal I run into this error: thread '<unnamed>' panicked at /home/dave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/youtube-tui-0.8.0/src/global/structs/mpv.rs:28:34:
                                                                  called `Result::unwrap()` on an `Err` value: VersionMismatch { linked: 65644, loaded: 131072 }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                               thread 'main' panicked at /home/dave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/youtube-tui-0.8.0/src/global/structs/mpv.rs:89:53:
                                                             called `Result::unwrap()` on an `Err` value: RecvError
 
I have the full backtrace as an attachment file:
[youtube-tui-backtrace.txt](https://github.com/Siriusmart/youtube-tui/files/13693017/youtube-tui-backtrace.txt)

Please let me know if you need any more information. I would love to try it out :-)

**Comment by Siriusmart** [comment]
hi this is a known issue, but it can easily be fixed.

the version on youtube-tui and the version on this git repo links to different version of libmpv, so to fix it you can try installing the tui via

```sh
cargo install --git https://github.com/siriusmart/youtube-tui
```

hope that works

**Comment by 5n00py** [comment]
It works. Looking good so far, thanks a lot!

**Comment by Siriusmart** [comment]
np
