### ISSUE TITLE
Freezing immediately after doing almost anything

### ISSUE THREAD

**Issue by SafriXV** [Siriusmart/youtube-tui#53]
I love the idea of this app but I'm having some issues setting it up, it worked for a (very) short time but now literally nothing loads, it's possible that adding subscriptions to my feed might have caused the problem as I think it started freezing after that (I could be wrong though). 

fyi, I've never used invidious before so I very well might have set things up wrong 

[subscriptions.json](https://github.com/Siriusmart/youtube-tui/files/15143287/subscriptions.json)
[main.txt](https://github.com/Siriusmart/youtube-tui/files/15143291/main.txt)
(the actual config is .yml I just did this so I can upload it)

Versions: (don't know what's helpful so I'll just do everything that might be important to know)
 - youtube-tui 0.8.0 (downloaded from the "youtube-tui-git" aur package)
 - mpv 0.38.0
 - yt-dlp 2024.04.09
 - kitty 0.33.1
 - zsh 5.9

**Comment by SafriXV** [comment]
Ok for some reason it was actually working for a little bit (I didn't do anything) but its broke again now so this might actually be an issue.

**Comment by Siriusmart** [comment]
every action in the TUI is blocking, meaning when you try to sync subscriptions, it will wait until all the subscriptions are synced before unfreezing again, this is likely an issue with invidious as they havent been fast for almost a year now

which is not something i could do, i might be putting some actual effort on the rewrite #48 where i could add an option to use newpipe instead, but for now, just deal with it

if u dont mind using a browser for youtube, you can get a similar, invidious-like experience with the [unhook extension](https://addons.mozilla.org/en-US/firefox/addon/youtube-recommended-videos/)

i have exams, so yeah...

**Comment by Siriusmart** [comment]
try switching invidous instances, vid.puffyan.us was the main instance when i was working on the tui, but now its horrendously slow, so do change that
