### ISSUE TITLE
Add debian packages

### ISSUE THREAD

**Issue by HumanG33k** [Siriusmart/youtube-tui#55]
Best option is to add stable and testing support. 

it can wait the new version of youtube-tui

thx a lot

**Comment by Siriusmart** [comment]
any new versions of youtube-tui will be a rewrite living as a component in ccanvas, however as mentioned in this post #48 the rewrite has stalled, so in the near future there wouldn't be any updates to this project

in an ideal world ccanvas will have its own component manager, but that's too far in the future to be sure, the earliest start-writing-code-again date is during the summer holidays, so I am closing this as no planned.
