### ISSUE TITLE
attempting to open annihilates console 

### ISSUE THREAD

**Issue by iLostMyXbox21** [Siriusmart/youtube-tui#56]
hello, i am using Arch linux with plasma 6.0.5. attempting to start by typing 'youtube-tui` causes this to be printed to the console

![image](https://github.com/Siriusmart/youtube-tui/assets/107326936/a98760e7-dd1a-4564-ba38-22c3ab0071b5)

additionally, my commands are now blank and most attempts to write a command (almost like its a password, its just hidden), leads the console to read as such

![image](https://github.com/Siriusmart/youtube-tui/assets/107326936/f001d1bd-022e-4b9d-97cc-486a2f24a71c)

installation went smoothly, had to install 2 dependencies but after those were installed it worked fine. no error message. restarting Konsole is the only way to get it to function again properly

also, while writing this i noticed that  'neofetch' has this output

![image](https://github.com/Siriusmart/youtube-tui/assets/107326936/e425e5d2-3f58-4e53-8cbe-6ed7ba6b6e8c)

im sure i likely did something wrong or am missing a dependency, but i installed it as i do all other AUR repos. any help is appreciated. running rust 1.78.0

**Comment by Brandonh2011** [comment]
I am having this exact issue as well. I installed it twice using 'yay -S youtube-tui' 

first time, i cose to remove make dependencies after install

second time, i cose to keep them, same issue. I am going to try one of the other recommended install methods and report back. 

I am using arch, i3, kitty terminal

**Comment by Brandonh2011** [comment]
tried install via cargo install youtube-tui, no dice

cargo install --git https://github.com/siriusmart/youtube-tui, same error

git clone and makepkg, nada

my system is fully up to date as well, so no potential out of date packages

**Comment by Siriusmart** [comment]
> tried install via cargo install youtube-tui, no dice
> 
> cargo install --git https://github.com/siriusmart/youtube-tui, same error
> 
> git clone and makepkg, nada
> 
> my system is fully up to date as well, so no potential out of date packages

version on crates.io links to the wrong version of libmpv for arch, the git version should work fine, but in case it doesnt, u can install it without the embedded player with

```sh
cargo install --git https://github.com/siriusmart/youtube-tui --no-default-features [add the features u need here]
```

for more about features, [read this](https://siriusmart.github.io/youtube-tui/installation.html)

**Comment by Siriusmart** [comment]
also, to un-nuke ur term, type `reset`

because when the tui starts, it enters the terminal raw mode, when it crashes, it doesnt exit raw mode as intended

**Comment by Brandonh2011** [comment]
using the youtube-tui-git package has worked for me. Thanks
