### ISSUE TITLE
youtube-tui hangs on "loading channel details"

### ISSUE THREAD

**Issue by manuelcicca** [Siriusmart/youtube-tui#58]
Hello,

I'm on NixOS unstable, Hyprland as wm and Kitty as terminal. I can search videos but once I select and hit enter the program hangs on "loading channel details". I did try to switch invidious instance and also disabled images yet the problem persists. 

Hope somebody can help
Thanks !

**Comment by Siriusmart** [comment]
please note that this is almost certainly a problem with invidious, they are fighting their own war, but the general rule of thumb would be, any crash is a problem with this TUI, while any hanging is awaiting a response from invidious.

there is nothing we can do, but i just checked, im using vid.puffyan.us, and the response time seems pretty good.

also, another tip to see if the instance is ok would be to try load a video on the instance
