### ISSUE TITLE
Invalid request error

### ISSUE THREAD

**Issue by Postboote1** [Siriusmart/youtube-tui#59]
Hello

I wanted to try this programm. Sadly every time i try to load a video I get the message "Invalid request : This helps protect our community. Learn more.
But the video won't load.

![Bildschirmfoto_20240721_115909](https://github.com/user-attachments/assets/ec467b38-152b-4192-a07d-f7d4202c86ac)

Any ideas how i could get it working??

**Comment by Siriusmart** [comment]
> Invalid request : This helps protect our community. Learn more.

https://github.com/iv-org/invidious/issues/4734

It's from invidious, can't rly do much about it, try switching instance im main.yml
https://api.invidious.io/
https://siriusmart.github.io/youtube-tui/config/main.html

**Comment by kqvanity** [comment]
Attempted to add `https://inv.nadeko.net` but getting `IO error` everytime I query something.
