### ISSUE TITLE
Cannot leave video actions menu

### ISSUE THREAD

**Issue by Zaedus** [Siriusmart/youtube-tui#6]
![image](https://user-images.githubusercontent.com/42098470/178157758-d9aef337-b328-4896-8103-541edac6ca2d.png)

**Comment by Siriusmart** [comment]
Can you please give more details to this one?

**Comment by Zaedus** [comment]
The menu where it shows the different ways to play or download a video doesn't have a back button or a perceivable way to go back to the trending tab.

**Comment by Siriusmart** [comment]
> The menu where it shows the different ways to play or download a video doesn't have a back button or a perceivable way to go back to the trending tab.

Use home button on your keyboard

**Comment by Siriusmart** [comment]
I don't really know what's going on but check if the v0.4.4 got this fixed
