### ISSUE TITLE
youtube-tui crashes immediately when invoked

### ISSUE THREAD

**Issue by ace510** [Siriusmart/youtube-tui#61]
I get the following message after building and running yotube-tui

` thread '<unnamed>' panicked at /home/ianclark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/youtube-tui-0.8.0/src/global/structs/mpv.rs:28:34:
                               called `Result::unwrap()` on an `Err` value: VersionMismatch { linked: 65644, loaded: 131074 }
       note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                    thread 'main' panicked at /home/ianclark/.cargo/registry/src/index.crates.io-6f17d22bba15001f/youtube-tui-0.8.0/src/global/structs/mpv.rs:87:14:
                                                                                                              called `Result::unwrap()` on an `Err` value: SendError { .. } `

cargo --version
cargo 1.80.1 (376290515 2024-07-16)

cargo install youtube-tui
    Updating crates.io index
     Ignored package `youtube-tui v0.8.0` is already installed, use --force to override

let me know if there's any more info that would be useful

**Comment by Siriusmart** [comment]
install git version with 
```
cargo install --git https://github.com/Siriusmart/youtube-tui
```

this is a known issue and there are no plans to push the fix it to cargo cuz im lazy

**Comment by ace510** [comment]
too lazy to change the docs either lol

**Comment by Siriusmart** [comment]
> too lazy to change the docs either lol

shh we dont talk about that here

in all seriousness, fetching video info from a centralised proxy (such as invidious) is a bad approach anyways, especially when youtube is actively trying to block web scrapers, the next gen youtube apps need to do that locally, such as by yt-dlp, which could be implemented to this ancient code ive not touched in years, but back to the main point, im too lazy at this moment

**Comment by Siriusmart** [comment]
when you want to download a video, yt-dlp is used to do so, but we still grab content from invidious via a standard web request
