### ISSUE TITLE
Nix build failing (help wanted)

### ISSUE THREAD

**Issue by Siriusmart** [Siriusmart/youtube-tui#62]
Hey if you use Nix, I would like some help.

[Nix builds are failing](https://github.com/Siriusmart/youtube-tui/actions/runs/10949448950/job/30402705270), if I'm guessing correctly, it is not being updated in the Nix repos, so it would be great if someone can fix that.

**Comment by jonboh** [comment]
I've sent a PR that should fix this ;) https://github.com/Siriusmart/youtube-tui/pull/63
thanks for this nice project!
