### ISSUE TITLE
API returned error: This content isn't available

### ISSUE THREAD

**Issue by chillmatin** [Siriusmart/youtube-tui#64]
When i try to open a video this error pops up. 
![image](https://github.com/user-attachments/assets/07a48d10-a85c-4c46-8f1a-5a0ec231282b)

**Comment by Siriusmart** [comment]
then its probably not available

perhaps [changing instances](https://siriusmart.github.io/youtube-tui/config/main.html#invidious_instance) to [one of these](https://vidiup.siri.sh/finder) will help
