### ISSUE TITLE
API returned error: Please sign in

### ISSUE THREAD

**Issue by haberturdeur** [Siriusmart/youtube-tui#65]
Hi, when I try to open (not play) a video I get the error: `API returned error: Please sign in`.
I tried to add the yt-dlp `--cookies-from-browser` wherever I could (yt-dlp config, mpv config, youtube-tui yt-dlp command, but it did not help. yt-dlp works on its own, so does mpv with yt-dlp.

Am I missing something?

Thank you.

Edit: it apparently happens everywhere, except for the cached ones. It worked fine before, after hibernation it doesn't.

**Comment by Siriusmart** [comment]
youtube-tui does not use yt-dlp for video info (may change soon), the error message happens perhaps because the instance ur using is blocked, u can fix this by changing to [one of these instances](https://vidiup.siri.sh/finder) in your main.yml

**Comment by haberturdeur** [comment]
That helped! Thank you for the quick response!
