### ISSUE TITLE
API returned error: Please sign in

### ISSUE THREAD

**Issue by 404ishan** [Siriusmart/youtube-tui#66]
i'm not really sure why its returning this error, i have signed into firefox but the error still remains.
![image](https://github.com/user-attachments/assets/a37d1df1-9f51-424b-9530-6eb6e73e63ed)

**Comment by tr1xem** [comment]
Facing same issue

**Comment by Siriusmart** [comment]
same solution as #64

**Comment by tr1xem** [comment]
Still the same ig its issue with invid itself

**Comment by 404ishan** [comment]
> same solution as #64

well, changing the instance did help with the sign-in error, i added in the full link and reloaded the config. now the only problem that remains is that the player doesn't seem to play any video nor any audio.

**Comment by 404ishan** [comment]
the mpv player issue seems to be within my computer, i think i fixed the issue with install the mpv player from the AUR and installing yt-dl along with it. thanks for the help! issue closed.
