### ISSUE TITLE
Fixxing youtube and invidious

### ISSUE THREAD

**Issue by otocotara** [Siriusmart/youtube-tui#67]
Ik that yt-tui is being rewritten and all but there is a really easy fix to at least make youtube-tui usable for now.

basically, everything but the video (searching, meta, etc...) works on invidious, and yt-dlp can still download the videos

instead of failing we could just download the video with yt-dlp to a cache and play it

probable cause of fail: invidious cant resolve the embed-url

**Comment by Siriusmart** [comment]
you could use ctrl-c to copy the url, even if the video doesnt load, and play it with mpv

otherwise, same solution as #64
