### ISSUE TITLE
"Cannot deserialize response: trailing characters at line 1 column 5" on search

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Siriusmart/youtube-tui#69]
1. Downloaded
2. Entered to search `Minsk`
3. Enter

**Comment by Siriusmart** [comment]
Try switching your instance, YouTube is blocking invidious and theres nothing I could do about it.

- [Active instance finder](https://vidiup.siri.sh/finder)
- [Switching instance](https://siriusmart.github.io/youtube-tui/config/main.html#invidious_instance)

![image](https://github.com/user-attachments/assets/195ce2a8-3a47-4b23-b281-8581177cf338)
