### ISSUE TITLE
Permissions denied

### ISSUE THREAD

**Issue by Slushee-a** [Siriusmart/youtube-tui#7]
I installed the package on arch linux with cargo, but it doesn't run unless it's run as root:
`Error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }`
I have previously done the same on void linux and I haven't needed to use root.

I'm guessing I need to be in some group. Which one is it?

**Comment by Siriusmart** [comment]
mb apparently it tries to remove everything in `~/.cache` on start, which is not intended, that might be what is causing the errors

**Comment by Siriusmart** [comment]
updated see if the error is still there

**Comment by Slushee-a** [comment]
It is fixed! Thank you.
