### ISSUE TITLE
Feature request: binary without embedded mpv

### ISSUE THREAD

**Issue by kenderipa** [Siriusmart/youtube-tui#73]
Hello, could you please provide a binary without embedded mpv, so it could start without mpv installed? Thanks!

**Comment by Siriusmart** [comment]
https://siriusmart.github.io/youtube-tui/installation.html#features

just install without the feature `mpv`

youtube-tui-nodefaults_arch-x86_64 in releases does not include embedded mpv, but it doesnt have image previews either, so maybe compiling is still the better option
